### ISSUE TITLE
No Traverse 180 Mode on latest slicer extension

### ISSUE THREAD

**Issue by mehrtash** [SlicerIGT/VolumeResliceDriver#9]
I downloaded today's Slicer nightly (4.4.0-2015-04-05 r24159) and got SlicerIGT from extension manager. Volume reslice driver doesn't have "Traverse 180" Mode.

**Comment by ungi** [comment]
HI Alireza. Those options have been moved to the "Advanced options" area. Check "Show advanced options" to enable extra widgets on the GUI. Note that now any orientation is allowed, not just the 8 on the old GUI. You probably need to select Transverse, and set the Rotation to 180.

BTW, we will disable these github issues, and such questions will need to be posted on the slicer-users or slicer-devel list.

Thanks,
Tamas
